services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: pgvector-db
    environment:
      POSTGRES_DB: vector_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
