INSERT INTO product_categories (name, description) VALUES
  ('Електроніка', 'Смартфони, ноутбуки та аксесуари для щоденної роботи'),
  ('Дім і кухня', 'Техніка та корисні речі для затишного побуту'),
  ('Офіс і навчання', 'Рішення для робочого місця та навчання'),
  ('Авто та інструменти', 'Обладнання для авто та побутового ремонту'),
  ('Туризм і спорт', 'Спорядження для активного відпочинку'),
  ('Краса та здоров''я', 'Догляд за собою та товари для відновлення');

INSERT INTO suppliers (name, contact_email, reliability_score) VALUES
  ('СвітТех Поставка', 'sales@svitteh.ua', 92),
  ('Балтія Логістик', 'orders@balticlogi.eu', 88),
  ('Карпати Трейд', 'hello@karpatytrade.ua', 81),
  ('Дунай Імпорт', 'support@danubeimport.eu', 85),
  ('Полісся Маркет', 'contact@polissya.market', 76);

INSERT INTO products (name, description, price, quantity, category_id, supplier_id) VALUES
  ('Бездротова миша', 'Ергономічна форма з м’яким покриттям, 6 програмованих кнопок, сенсор 16000 DPI, робота від акумулятора до 70 годин, одночасне підключення Bluetooth і 2.4 ГГц.', 1299, 140,
   (SELECT id FROM product_categories WHERE name = 'Електроніка'),
   (SELECT id FROM suppliers WHERE name = 'СвітТех Поставка')),
  ('Навушники з шумопоглинанням', 'Bluetooth 5.3 з мультипоінтом, режим прозорості, активне шумопоглинання до 40 дБ, до 35 годин автономності, швидка зарядка USB-C за 10 хвилин на 5 годин музики.', 3699, 65,
   (SELECT id FROM product_categories WHERE name = 'Електроніка'),
   (SELECT id FROM suppliers WHERE name = 'Балтія Логістик')),
  ('Мультиварка 5л', '11 програм приготування, антипригарна чаша з товстими стінками, відкладений старт до 24 годин, підтримка підігріву і автоприготування каш, супів та випічки.', 2899, 48,
   (SELECT id FROM product_categories WHERE name = 'Дім і кухня'),
   (SELECT id FROM suppliers WHERE name = 'Карпати Трейд')),
  ('Регульований офісний стіл', 'Електропривід із двома моторами, 4 профілі пам’яті висот, система кабель-менеджменту з металевим лотком, антиколізійний захист та діапазон висоти 62–125 см.', 8799, 22,
   (SELECT id FROM product_categories WHERE name = 'Офіс і навчання'),
   (SELECT id FROM suppliers WHERE name = 'Дунай Імпорт')),
  ('Настільна лампа з Qi зарядкою', 'LED лампа з 4 колірними температурами, бездротова зарядка 15 Вт, два USB-порти, сенсорне керування яскравістю, таймер сну і шарнірне кріплення під різні кути.', 1890, 75,
   (SELECT id FROM product_categories WHERE name = 'Офіс і навчання'),
   (SELECT id FROM suppliers WHERE name = 'СвітТех Поставка')),
  ('Трекінговий рюкзак 45л', 'Посилена спинка з вентиляцією, регульована система підвісу, кріплення для трекінгових палиць, відділення для ноутбука та гермомішок для мокрих речей.', 3490, 38,
   (SELECT id FROM product_categories WHERE name = 'Туризм і спорт'),
   (SELECT id FROM suppliers WHERE name = 'Полісся Маркет')),
  ('Намет на 3 особи', 'Двошаровий тент з водостійкістю 5000 мм, алюмінієві дуги, снігові спідниці, два тамбури, великі вентиляційні вікна та світловідбивні стропи.', 5120, 19,
   (SELECT id FROM product_categories WHERE name = 'Туризм і спорт'),
   (SELECT id FROM suppliers WHERE name = 'Балтія Логістик')),
  ('Масажний пістолет', '6 насадок для різних груп м’язів, 5 швидкостей до 3200 уд/хв, акумулятор 2500 мА·год до 4 годин роботи, металевий корпус і тихий мотор 40 дБ.', 2790, 54,
   (SELECT id FROM product_categories WHERE name = 'Краса та здоров''я'),
   (SELECT id FROM suppliers WHERE name = 'Карпати Трейд')),
  ('Компресор автомобільний', 'Цифровий манометр з автостопом, металевий циліндр, вбудований ліхтарик, пам’ять цільового тиску та набір перехідників для авто, матраців і м’ячів.', 2150, 102,
   (SELECT id FROM product_categories WHERE name = 'Авто та інструменти'),
   (SELECT id FROM suppliers WHERE name = 'Полісся Маркет')),
  ('Набір гайкових ключів 24 шт.', 'Хром-ванадієва сталь, тріскачка 72 зубці, ударостійкий кейс з підписаними гніздами, розміри від 8 до 32 мм та подовжені головки для важкодоступних місць.', 3990, 34,
   (SELECT id FROM product_categories WHERE name = 'Авто та інструменти'),
   (SELECT id FROM suppliers WHERE name = 'Дунай Імпорт')),
  ('Ультрабук 14" Ryzen', 'Тонкий металевий корпус 1.2 кг, процесор Ryzen 7 7840U, 16 ГБ RAM, NVMe 1 ТБ, батарея на 16 годин, екран 2.8K з тонкими рамками.', 28990, 27,
   (SELECT id FROM product_categories WHERE name = 'Електроніка'),
   (SELECT id FROM suppliers WHERE name = 'СвітТех Поставка')),
  ('Смарт-годинник з GPS', 'AMOLED 1.43", подвійний GPS, оптичний датчик пульсу та SpO2, автономність до 12 днів, водозахист 5 ATM, 120 режимів тренувань.', 5299, 58,
   (SELECT id FROM product_categories WHERE name = 'Електроніка'),
   (SELECT id FROM suppliers WHERE name = 'Балтія Логістик')),
  ('Робот-пилосос з лідаром', 'Лідарна навігація з картами кількох поверхів, сила всмоктування 5000 Па, мийка з електронним дозуванням води, підтримка голосових команд.', 16499, 21,
   (SELECT id FROM product_categories WHERE name = 'Дім і кухня'),
   (SELECT id FROM suppliers WHERE name = 'Карпати Трейд')),
  ('Повітряний зволожувач', 'Ультразвуковий, резервуар 5 л, продуктивність 350 мл/год, нічний режим, індикація вологості та ароматизація ефірними маслами.', 2390, 61,
   (SELECT id FROM product_categories WHERE name = 'Дім і кухня'),
   (SELECT id FROM suppliers WHERE name = 'СвітТех Поставка')),
  ('Настільний органайзер з бамбуку', 'Багаторівневі відділення для паперу та дрібниць, тримач для смартфона, лоток для кабелів, екологічний лакований бамбук.', 990, 120,
   (SELECT id FROM product_categories WHERE name = 'Офіс і навчання'),
   (SELECT id FROM suppliers WHERE name = 'Полісся Маркет')),
  ('Офісне крісло ергономічне', 'Сітчаста спинка, регульована поперекова підтримка, 3D-підлокітники, газліфт класу 4, нахил спинки до 135° та сталева база.', 6290, 44,
   (SELECT id FROM product_categories WHERE name = 'Офіс і навчання'),
   (SELECT id FROM suppliers WHERE name = 'Дунай Імпорт')),
  ('Перфоратор SDS-plus', 'Двигун 1200 Вт, сила удару 4.5 Дж, режими свердління та довбання, антивібраційна рукоятка, кейс і набір бурів у комплекті.', 4890, 52,
   (SELECT id FROM product_categories WHERE name = 'Авто та інструменти'),
   (SELECT id FROM suppliers WHERE name = 'Карпати Трейд')),
  ('Лазерний рівень 360°', 'Три площини по 360°, зелений промінь, самовирівнювання, живлення від акумулятора та батарей, магнітний кронштейн і штатив.', 3590, 47,
   (SELECT id FROM product_categories WHERE name = 'Авто та інструменти'),
   (SELECT id FROM suppliers WHERE name = 'Балтія Логістик')),
  ('Пуско-зарядний пристрій 12000 мА·год', 'Піковий струм 1200 А для бензинових і дизельних авто, вбудований ліхтарик SOS, два USB-порти для гаджетів, інтелектуальний захист від переполюсовки.', 4290, 33,
   (SELECT id FROM product_categories WHERE name = 'Авто та інструменти'),
   (SELECT id FROM suppliers WHERE name = 'СвітТех Поставка')),
  ('Спальний мішок -5°C', 'Синтетичний наповнювач, комфортна температура -5°C, двостороння блискавка з теплим клапаном, капюшон зі стяжкою, компресійний мішок.', 2190, 59,
   (SELECT id FROM product_categories WHERE name = 'Туризм і спорт'),
   (SELECT id FROM suppliers WHERE name = 'Полісся Маркет')),
  ('Газовий пальник туристичний', 'Складні лапки з нержавійки, регулювання полум’я, 3200 Вт потужності, п’єзопідпал та жиклер для роботи у холоді.', 890, 130,
   (SELECT id FROM product_categories WHERE name = 'Туризм і спорт'),
   (SELECT id FROM suppliers WHERE name = 'Дунай Імпорт')),
  ('Каремат самонадувний', 'Товщина 5 см, клапан зворотного тиску, армована поверхня проти ковзання, ремені для фіксації в рулоні та ремкомплект у наборі.', 1250, 83,
   (SELECT id FROM product_categories WHERE name = 'Туризм і спорт'),
   (SELECT id FROM suppliers WHERE name = 'Балтія Логістик')),
  ('Електрична зубна щітка', 'Ультразвукові коливання 40000 в/х, 5 режимів чищення, тиждень роботи від однієї зарядки, датчик тиску та таймер на 2 хвилини.', 1790, 93,
   (SELECT id FROM product_categories WHERE name = 'Краса та здоров''я'),
   (SELECT id FROM suppliers WHERE name = 'СвітТех Поставка')),
  ('Фітнес-трекер', 'Моніторинг пульсу та SpO2, трекінг сну, до 14 днів роботи без підзарядки, водозахист 5 ATM, повідомлення зі смартфона.', 2299, 88,
   (SELECT id FROM product_categories WHERE name = 'Краса та здоров''я'),
   (SELECT id FROM suppliers WHERE name = 'Полісся Маркет')),
  ('Професійний фен', 'Безщітковий мотор 110000 об/хв, іонізація, 3 температурні режими, 2 насадки-концентратори й дифузор, вага лише 430 г.', 5190, 36,
   (SELECT id FROM product_categories WHERE name = 'Краса та здоров''я'),
   (SELECT id FROM suppliers WHERE name = 'Дунай Імпорт')),
  ('Йогуртниця на 8 банок', '8 скляних баночок по 200 мл, електронний таймер до 12 годин, рівномірний підігрів, захист від перегріву та індикатор готовності.', 1450, 42,
   (SELECT id FROM product_categories WHERE name = 'Дім і кухня'),
   (SELECT id FROM suppliers WHERE name = 'Карпати Трейд')),
  ('Блендер погружний 1200 Вт', 'Металевий ніж з титановим покриттям, турборежим, вінчик і подрібнювач у комплекті, плавне регулювання швидкості.', 2290, 77,
   (SELECT id FROM product_categories WHERE name = 'Дім і кухня'),
   (SELECT id FROM suppliers WHERE name = 'СвітТех Поставка')),
  ('Док-станція USB-C 9-в-1', 'Підтримка PD 100 Вт, HDMI 4K 60 Гц, 3 USB-A, Ethernet, зчитувач карт SD/MicroSD, алюмінієвий корпус і кабель 15 см.', 2790, 91,
   (SELECT id FROM product_categories WHERE name = 'Офіс і навчання'),
   (SELECT id FROM suppliers WHERE name = 'Балтія Логістик')),
  ('Монітор 27" QHD 165Гц', 'IPS-матриця з охопленням sRGB 99%, частота 165 Гц з FreeSync, тонкі рамки, регулювання висоти та поворот у портретний режим.', 11890, 29,
   (SELECT id FROM product_categories WHERE name = 'Електроніка'),
   (SELECT id FROM suppliers WHERE name = 'Дунай Імпорт')),
  ('Зовнішній SSD 1 ТБ', 'Швидкість читання до 1050 МБ/с, алюмінієвий корпус із гумовими вставками, захист від падіння до 2 м, інтерфейс USB-C 3.2 Gen2.', 4490, 73,
   (SELECT id FROM product_categories WHERE name = 'Електроніка'),
   (SELECT id FROM suppliers WHERE name = 'Полісся Маркет'));

INSERT INTO customers (name, email, loyalty_tier) VALUES
  ('Олена Коваль', 'olena.koval@example.com', 'Gold'),
  ('Ігор Мельник', 'ihor.melnyk@example.com', 'Silver'),
  ('Марія Ткач', 'maria.tkach@example.com', 'Bronze');

INSERT INTO purchase_orders (customer_id, product_id, quantity, status) VALUES
  ((SELECT id FROM customers WHERE name = 'Олена Коваль'),
   (SELECT id FROM products WHERE name = 'Бездротова миша'), 3, 'completed'),
  ((SELECT id FROM customers WHERE name = 'Олена Коваль'),
   (SELECT id FROM products WHERE name = 'Настільна лампа з Qi зарядкою'), 2, 'completed'),
  ((SELECT id FROM customers WHERE name = 'Ігор Мельник'),
   (SELECT id FROM products WHERE name = 'Компресор автомобільний'), 4, 'processing'),
  ((SELECT id FROM customers WHERE name = 'Ігор Мельник'),
   (SELECT id FROM products WHERE name = 'Намет на 3 особи'), 1, 'processing'),
  ((SELECT id FROM customers WHERE name = 'Марія Ткач'),
   (SELECT id FROM products WHERE name = 'Смарт-годинник з GPS'), 1, 'pending'),
  ((SELECT id FROM customers WHERE name = 'Марія Ткач'),
   (SELECT id FROM products WHERE name = 'Трекінговий рюкзак 45л'), 2, 'pending'),
  ((SELECT id FROM customers WHERE name = 'Ігор Мельник'),
   (SELECT id FROM products WHERE name = 'Лазерний рівень 360°'), 1, 'shipped'),
  ((SELECT id FROM customers WHERE name = 'Олена Коваль'),
   (SELECT id FROM products WHERE name = 'Ультрабук 14" Ryzen'), 1, 'processing'),
  ((SELECT id FROM customers WHERE name = 'Марія Ткач'),
   (SELECT id FROM products WHERE name = 'Повітряний зволожувач'), 2, 'completed'),
  ((SELECT id FROM customers WHERE name = 'Ігор Мельник'),
   (SELECT id FROM products WHERE name = 'Газовий пальник туристичний'), 3, 'shipped'),
  ((SELECT id FROM customers WHERE name = 'Олена Коваль'),
   (SELECT id FROM products WHERE name = 'Масажний пістолет'), 1, 'completed'),
  ((SELECT id FROM customers WHERE name = 'Марія Ткач'),
   (SELECT id FROM products WHERE name = 'Пуско-зарядний пристрій 12000 мА·год'), 1, 'processing'),
  ((SELECT id FROM customers WHERE name = 'Ігор Мельник'),
   (SELECT id FROM products WHERE name = 'Офісне крісло ергономічне'), 2, 'pending');
